version: '3.8'

services:
  db:
    image: postgres:15.0-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 5s
      timeout: 5s
      retries: 5

    ports:
      - "5434:5432"
    volumes:
      - pg_data_master:/var/lib/postgresql/data

volumes:
  pg_data_master:
