# Generated by Django 4.1.7 on 2023-03-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='product',
        ),
        migrations.AddField(
            model_name='link',
            name='product',
            field=models.ManyToManyField(
                blank=True, related_name='sellers', to='link.product'
            ),
        ),
    ]
