# Generated by Django 4.1.7 on 2023-03-11 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='legal_name',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='link.businessunit',
                verbose_name='legal_name',
            ),
        ),
    ]
