# Generated by Django 4.1.7 on 2023-03-10 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_remove_link_product_link_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='link.supplier',
            ),
        ),
    ]
